### PR TITLE
Iss 907

### PR DESCRIPTION
**Pull request by burkmarr**
Makes license selection mandatory only if the form is a user registration form. Otherwise non-mandatory. For https://github.com/BiologicalRecordsCentre/iRecord/issues/907#issuecomment-674825868. (Previous fix for the iRecord over 13 field which was originally in this branch is being moved to an iRecord specific module.)

### CODE REVIEW

**Comment by johnvanbreda** [comment]
@burkmarr do you need this merged into master soon?

**Comment by burkmarr** [comment]
@johnvanbreda - if possible that would be good.

**Comment by johnvanbreda** [comment]
@burkmarr I've done that now - a full release of v4.4 for the warehouse plus Drupal 7 & 8 modules. I've upgraded the warehouse but not iRecord - it might make sense to do this when you are ready to complete any configuration/checks needed rather than last think on a Friday?

**Comment by burkmarr** [comment]
Agreed John - I'll take a look on Monday. Many thanks for preparing the release.

**Comment by burkmarr** [comment]
@BirenRathod or @johnvanbreda - some questions about to updating iRecord live:

1. Do we do this with Git pull from master?
2. Do we do a recursive pull into iForm to get the sub-modules or separate pulls in media and client_helpers?
3. Do we put the site into maintenance mode while we do any of this?

**Comment by johnvanbreda** [comment]
In theory - from the iform folder:
```
$ git pull --recursive
```

In practice I experienced this not working as I thought once, so I normally check the branch is master, then git pull and then repeat on both client_helpers and media. Then don't forget to clear the Drupal cache on iRecord as the JavaScript files will be different.

Normally the whole process only takes a few seconds and is not likely to leave the site unusable while in progress so I don't use maintenance mode. Otherwise we may cause issues for people half way through data entry.

Let me know if you want me to do it.

**Comment by burkmarr** [comment]
Thanks @johnvanbreda - I'll have a go now.

**Comment by burkmarr** [comment]
That seems to have worked correctly.

**Pull request merged**
