### PR TITLE
Lic text

### PR DESCRIPTION
**Pull request by burkmarr**
@johnvanbreda - pull request of license media text update into master.

### CODE REVIEW

**Comment by burkmarr** [comment]
Don't merge this yet - @johnvanbreda - I just noticed a mistake.

**Comment by burkmarr** [comment]
@johnvanbreda - good to go now.

**Comment by johnvanbreda** [comment]
Merged and pulled onto iRecord.

**Comment by burkmarr** [comment]
Thanks @johnvanbreda - I just merged into dev.

**Pull request merged**
